### ISSUE TITLE
Types not working correctly

### ISSUE THREAD

**Issue by mtt87** [Temzasse/stitches-native#20]
EDIT: sorry I accidentally pressed enter and created the empty issue 😆 

First of all thanks for creating this library, I'm testing it and I found this issue where types are not working.
![Screenshot 2021-10-20 at 13 54 51](https://user-images.githubusercontent.com/2150927/138097231-c537e77b-b5c8-4a98-8b16-73caf0187fd4.png)

It should suggest `fontFamily`, `fontSize` etc but it's not

That said, once I write `fontFamily: "` then I get the correct autocomplete based on my tokens.
![Screenshot 2021-10-20 at 13 55 01](https://user-images.githubusercontent.com/2150927/138097318-47b52df5-cc08-4166-9178-29ccab6a580c.png)

```
"react-native": "0.65.1",
"typescript": "^4.4.4"
"stitches-native": "^0.0.1-4"
```

EDIT: I just realised I can also do this but still the issue is there
```js
import { Text as TextComponent } from 'react-native'
const Text = styled(TextComponent, {
// same as
const Text = styled('Text', {
```

**Comment by mtt87** [comment]
Second issue related to types, in the compound variant it's not happy
```js
variants: {
  color: {
    red: {
       backgroundColor: theme.colors.red500, // ✅  all good here
   } 
  }
},
compoundVariants: [
    {
      color: 'red',
      variant: 'solid',
      css: {
        backgroundColor: theme.colors.red500, // ❌  TS error here
      },
    },
]
```
TS error:
```
Property 'backgroundColor' is incompatible with index signature.
            Type 'Token<"red500", string, "colors">' is not assignable to type 'string | number | boolean | WideObject'.
              Type 'Token<"red500", string, "colors">' is not assignable to type 'WideObject'.
                Index signature for type 'string' is missing in type 'Token<"red500", string, "colors">'.
```

But if I use `theme.colors.red500.value` it doesn't throw an error

**Comment by mtt87** [comment]
Using the shortcut for theme token with `${value}` doesn't work for `fontWeight` but it works for `fontFamily` and other properties.
```js
const Heading = styled(TextComponent, {
  fontFamily: '$inter', // ✅ 
  fontWeight: '$700', // ❌ 
})
```
```js
const Heading = styled(TextComponent, {
  fontFamily: '$inter', // ✅ 
  fontWeight: theme.fontWeights[700], // ✅ 
})
```

**Comment by mtt87** [comment]
Another issue, negative token values don't seem to work they are treated as positive.
```js
const View = styled('View');

<View css={{ marginLeft: '$2' }}> 
<View css={{ marginLeft: '-$2' }}>
```
They both have the same output

**Comment by Temzasse** [comment]
> Using the shortcut for theme token with `${value}` doesn't work for `fontWeight` but it works for `fontFamily` and other properties.
> 
> ```js
> const Heading = styled(TextComponent, {
>   fontFamily: '$inter', // ✅ 
>   fontWeight: '$700', // ❌ 
> })
> ```
> 
> ```js
> const Heading = styled(TextComponent, {
>   fontFamily: '$inter', // ✅ 
>   fontWeight: theme.fontWeights[700], // ✅ 
> })
> ```

This issue should be fixed in the latest canary version. I had a typo in the default theme map which caused `fontWeight` not getting the autocomplete results for theme tokens 😅

**Comment by Temzasse** [comment]
> EDIT: sorry I accidentally pressed enter and created the empty issue 😆
> 
> First of all thanks for creating this library, I'm testing it and I found this issue where types are not working. ![Screenshot 2021-10-20 at 13 54 51](https://user-images.githubusercontent.com/2150927/138097231-c537e77b-b5c8-4a98-8b16-73caf0187fd4.png)
> 
> It should suggest `fontFamily`, `fontSize` etc but it's not
> 
> That said, once I write `fontFamily: "` then I get the correct autocomplete based on my tokens. ![Screenshot 2021-10-20 at 13 55 01](https://user-images.githubusercontent.com/2150927/138097318-47b52df5-cc08-4166-9178-29ccab6a580c.png)
> 
> ```
> "react-native": "0.65.1",
> "typescript": "^4.4.4"
> "stitches-native": "^0.0.1-4"
> ```
> 
> EDIT: I just realised I can also do this but still the issue is there
> 
> ```js
> import { Text as TextComponent } from 'react-native'
> const Text = styled(TextComponent, {
> // same as
> const Text = styled('Text', {
> ```

Hmm I can't seem to reproduce this issue locally 🤔 Does this still happen in the latest canary version?

**Comment by Temzasse** [comment]
> Another issue, negative token values don't seem to work they are treated as positive.
> 
> ```js
> const View = styled('View');
> 
> <View css={{ marginLeft: '$2' }}> 
> <View css={{ marginLeft: '-$2' }}>
> ```
> 
> They both have the same output

This should be now fixed in `v0.0.1-7` 🙂

**Comment by mtt87** [comment]
Thanks for the update! This is what I can see so far:
✅  negative properties working now `marginLeft: "-$2"`
✅  intellisense on `css` prop
![Screenshot 2021-10-23 at 13 26 41](https://user-images.githubusercontent.com/2150927/138557270-37dc0a22-7224-41e4-a53e-0e1923396c6e.png)

❌  intellisense on `styled('Component')` still not working for me
![Screenshot 2021-10-23 at 13 26 58](https://user-images.githubusercontent.com/2150927/138557267-cf3fe7eb-745b-41ac-85f6-7c7b6bdaf804.png)


❌  correct suggestion of properties not working, which btw works fine with the react native types
![Screenshot 2021-10-23 at 13 58 22](https://user-images.githubusercontent.com/2150927/138557390-a67a4eee-9195-40be-9cf5-98b80b3b466b.png)
![Screenshot 2021-10-23 at 13 58 32](https://user-images.githubusercontent.com/2150927/138557384-a0045979-aa12-4266-84fa-7214cd058822.png)


```
"react-native": "0.65.1",
"@types/react": "^17.0.31",
"@types/react-native": "^0.66.0",
"typescript": "^4.4.4"
```

**Comment by Temzasse** [comment]
> ❌ correct suggestion of properties not working, which btw works fine with the react native types
> ![Screenshot 2021-10-23 at 13 58 22](https://user-images.githubusercontent.com/2150927/138557390-a67a4eee-9195-40be-9cf5-98b80b3b466b.png)
> ![Screenshot 2021-10-23 at 13 58 32](https://user-images.githubusercontent.com/2150927/138557384-a0045979-aa12-4266-84fa-7214cd058822.png)

This is related to the currently unsolved issue of having all `Text` + `View` + `Image` style properties shown in the autocomplete: https://github.com/Temzasse/stitches-native/issues/18

I would love to fix this but it's quite complicated since the types are so complex 😅

**Comment by Temzasse** [comment]
> ❌ intellisense on `styled('Component')` still not working for me
> ![Screenshot 2021-10-23 at 13 26 58](https://user-images.githubusercontent.com/2150927/138557267-cf3fe7eb-745b-41ac-85f6-7c7b6bdaf804.png)

This is an odd one since I can't reproduce this locally with the dev version or the one released on npm 🤔 For me it works fine:

<img width="541" alt="Screenshot 2021-10-23 at 23 27 06" src="https://user-images.githubusercontent.com/6152032/138570660-afb7b23a-9f71-41a3-ad2a-1403eb3484b0.png">

Could you create a repro in a Github repo so that I could try it out?

**Comment by mtt87** [comment]
Sure, this is what I've done and the issue is still there:
```
$ npx react-native init MyApp --template react-native-template-typescript
$ cd MyApp
$ yarn add stitches-native@0.0.1-7
```
I tested with different versions of Typescript (v3 an but doesn't make any difference.
![Screenshot 2021-10-24 at 13 46 32](https://user-images.githubusercontent.com/2150927/138595879-1ce9b577-2074-4d42-932e-da3dafdbb991.png)

Here is the repo, I just changed `App.tsx` and added `stitches.config.ts`, everything else is standard RN template.

**Comment by Temzasse** [comment]
@mtt87 I followed your instructions and everything works just fine for me 😅 

Maybe you have misconfigured the Stitches config?

Here's the config I used for testing:

```ts

export const { styled, theme } = createStitches({
  theme: {
    colors: {
      // Palette
      blue100: '#ab9cf7',
      blue500: '#301b96',
      blue900: '#0D0630',
      black: '#222',
      white: '#fff',

      primary: '$blue500',
      primaryDark: '$blue900',
      primaryLight: '$blue100',
      secondary: '#8BBEB2',
      secondaryDark: '#384d48',
      secondaryLight: '#d9fff6',
      background: '$white',
      text: '$black',
    },
    space: {
      1: 4,
      2: 8,
      3: 16,
      4: 24,
      5: 32,
      6: 40,
      7: 56,
      8: 72,
      9: 96,
    },
    sizes: {
      hairlineWidth: StyleSheet.hairlineWidth,
    },
    radii: {
      sm: 4,
      md: 8,
      lg: 24,
      full: 999,
    },
  },
  utils: {
    size: (value: number) => ({
      width: value,
      height: value,
    }),
    flexCenter: (value?: Stitches.PropertyValue<'flexDirection'>) => ({
      flexDirection: value || 'row',
      justifyContent: 'center',
      alignItems: 'center',
    }),
    absoluteFill: () => ({
      ...StyleSheet.absoluteFillObject,
    }),
  },
});
```

<img width="506" alt="Screenshot 2021-10-27 at 9 52 05" src="https://user-images.githubusercontent.com/6152032/139014800-7a8cc324-782c-4c68-8fda-0c6ab1a6d113.png">

**Comment by mtt87** [comment]
That's interesting 🤔  

Could you try with my repo https://github.com/mtt87/debug-stitches-native-typescript ?
I just realised that I didn't paste the link in my previous message sorry.

Can you also double check what typescript are you using?
![Screenshot 2021-10-27 at 10 48 14](https://user-images.githubusercontent.com/2150927/139042426-5e7b523c-3730-4f04-83e7-865f8a6d0e26.png)

Thank you!

**Comment by Temzasse** [comment]
Okay now I'm getting the typing issue when I changed the TypeScript version. I think my example app was using the TypeScript of the `stitches-native` repo which was part of the same vscode workspace. Thanks for the tip 👍🏻 

Now I just need to figure out why on earth the types are not working properly 😭

**Comment by Temzasse** [comment]
@mtt87 I think I found the source of the TS bug 🐛🕵🏻‍♂️ 

The typings for `styled` component's CSS properties should work correctly now. Can you test the latest canary version (`v0.0.1-8`)? 🙂 

About all the remaining TS problems that have been commented under this issue: it would be better to move them to separate issues so that they can be tackled one by one more easily (and nothing gets lost in the sea of comments).

**Comment by mtt87** [comment]
🎉  great it's working now 😄 
![Screenshot 2021-10-31 at 22 42 27](https://user-images.githubusercontent.com/2150927/139603612-78a95ebe-8b2a-4307-8215-df24580cbb00.png)

Tomorrow when I have a moment I create separate issues, we can close this one, thank you for fixing it! 🙏
